# Generated by Django 3.2.15 on 2022-09-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('mobile_code', models.CharField(max_length=255)),
                ('time_zone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_launch', models.DateTimeField()),
                ('message', models.TextField()),
                ('mobile_code', models.CharField(max_length=255)),
                ('mailing_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='notification.client')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='notification.distribution')),
            ],
        ),
    ]
