# Generated by Django 3.2.15 on 2022-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['phone_number']},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ['mailing_launch']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='mobile_code',
            field=models.CharField(max_length=10),
        ),
    ]
