# Generated by Django 3.2.15 on 2022-09-24 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_distribution_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='message',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notification.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.distribution'),
        ),
    ]
